
name: Template
on:
  schedule: [{cron: "*/30 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - run: sleep 120
    - uses: actions/checkout@v2
    - run: git pull
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v1
      with:
        token: ${{ secrets.USER_TOKEN }}
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Update README"
        git pull
        git push
        fi
